name: CI

on: [push]

jobs:
  sast_scan:
    name: run Bandit scan
    runs-on : ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: install Bandit
      run: pip install bandit

    - name : run Bandit scan
      run: bandit -ll -ii -r . -f json -o bandit-report.json

    - name: upload artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit-findings
        path: bandit-report.json


  image_scan:
    name: build image and run image scan
    runs-on : ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v3
      with:
        version: 24.0.6   

    - name: build docker image
      run: docker build -f Dockerfile -t myapp:latest .

    - name: check default daemon json content
      run: |
        if [ -f /etc/docker/daemon.json ]; then
          cat /etc/docker/daemon.json
        else
          echo "{}" > /tmp/daemon.json
          cat /tmp/daemon.json
        fi

    - name : Docker scout scan
      run: |
        curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
        sh install-scout.sh

        echo ${{secrets.REPO_PWD}} | docker -login ${{secrets.REPO_USER}} --password-stdin
        
        docker scout quiekview
        docker scout cves

      
    
